version: "3.3"
   
services:
  db:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: yacosql
       MYSQL_USER: yacosql
       MYSQL_PASSWORD: yacosql
       MYSQL_ROOT_PASSWORD: yacosql
  web:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:7777
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:7777"
    depends_on:
      - db
